---
spring:
  profiles: default
  datasource:
    # url: "jdbc:sqlite::memory:"
    url: "jdbc:sqlite:/home/user/projects/bookstore/sqlite.db"
    driver-class-name: org.sqlite.JDBC
    # initialization-mode: alway
    initialization-mode: never